In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
pd.set_option('display.max_columns', None)


In [14]:
df=pd.read_csv('rotten_tomatoes_top_movies.csv')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                1610 non-null   int64  
 1   title                     1610 non-null   object 
 2   year                      1610 non-null   int64  
 3   synopsis                  1602 non-null   object 
 4   critic_score              1610 non-null   int64  
 5   people_score              1609 non-null   float64
 6   consensus                 1593 non-null   object 
 7   total_reviews             1610 non-null   int64  
 8   total_ratings             1610 non-null   object 
 9   type                      1610 non-null   object 
 10  rating                    1610 non-null   object 
 11  genre                     1610 non-null   object 
 12  original_language         1570 non-null   object 
 13  director                  1609 non-null   object 
 14  producer

In [15]:
df.tail(10)

Unnamed: 0              title  year  \
1600        1600    The Lone Ranger  2013   
1601        1601          The Alamo  2004   
1602        1602  The Warrior's Way  2010   
1603        1603     The Dark Tower  2017   
1604        1604     Wild Wild West  1999   
1605        1605             Priest  2011   
1606        1606     September Dawn  2006   
1607        1607   American Outlaws  2001   
1608        1608          Jonah Hex  2010   
1609        1609      Texas Rangers  2001   

                                               synopsis  critic_score  \
1600  In 1933 a boy discovers an ancient Native Amer...            30   
1601  In 1836 Gen. Sam Houston (Dennis Quaid) organi...            29   
1602  Refusing to kill an infant from an enemy clan,...            31   
1603  Roland Deschain (Idris Elba), the last Gunslin...            16   
1604  When President Ulysses S. Grant (Kevin Kline) ...            17   
1605  In a society ravaged by centuries of war betwe...            15   
1606  In 1857 Capt. Alexander Fancher leads a wagon ...            16   
1607  After the Civil War ends, Confederate soldiers...            14   
1608  Having cheated death, gunslinger and bounty hu...            12   
1609  Texas, 1875. In a land without justice, where ...             2   

      people_score                                          consensus  \
1600          51.0  Armie Hammer and Johnny Depp make for an appea...   
1601          45.0  Too conventional and uninvolving to be memorable.   
1602          47.0  Perfectly, thoroughly divisive, The Warrior's ...   
1603          45.0  Go then, there are other Stephen King adaptati...   
1604          28.0  Bombastic, manic, and largely laugh-free, Wild...   
1605          46.0  Sleek and stylish, but those qualities are was...   
1606          49.0  With its jarring editing, dull love story, and...   
1607          68.0  With corny dialogue, revisionist history, anac...   
1608          20.0  Josh Brolin gives it his best shot, but he can...   
1609          29.0  As far as westerns go, Texas Rangers is strict...   

      total_reviews total_ratings     type  \
1600            247       25,000+  Western   
1601            159       10,000+  Western   
1602             42       25,000+  Western   
1603            275       25,000+  Western   
1604            131      250,000+  Western   
1605            101       50,000+  Western   
1606             55        5,000+  Western   
1607            103       25,000+  Western   
1608            152      100,000+  Western   
1609             51        5,000+  Western   

                                                 rating  \
1600  PG-13 (Some Suggestive Material|Seq of Intense...   
1601                 PG-13 (Sustained Battle Sequences)   
1602                         R (Strong Bloody Violence)   
1603  PG-13 (Sequences of Gun Violence|Action|Themat...   
1604    PG-13 (Innuendo|Action/Violence|Sex References)   
1605  PG-13 (Disturbing Images|Brief Strong Language...   
1606                                       R (Violence)   
1607                           PG-13 (Western Violence)   
1608  PG-13 (Intense Sequences of Action|Disturbing ...   
1609                           PG-13 (Western Violence)   

                                                  genre original_language  \
1600                         western, adventure, action           English   
1601                                drama, history, war           English   
1602       western, action, fantasy, sports and fitness           English   
1603                         adventure, action, fantasy           English   
1604                            comedy, western, action           English   
1605                            horror, action, fantasy           English   
1606                            drama, history, western           English   
1607                                    western, action           English   
1608  mystery and thriller, fantasy, action, western

In [16]:
df['title'].unique()

array(['Black Panther', 'Avengers: Endgame',
       'Mission: Impossible -- Fallout', 'Mad Max: Fury Road',
       'Spider-Man: Into the Spider-Verse', 'Wonder Woman', 'Dunkirk',
       'Coco', 'Thor: Ragnarok', 'Logan', 'Star Wars: The Last Jedi',
       'Star Wars: The Force Awakens', 'The Adventures of Robin Hood',
       'King Kong', 'Spider-Man: Far From Home', 'Incredibles 2',
       'Zootopia', 'War for the Planet of the Apes',
       'Spider-Man: Homecoming', 'Baby Driver', 'Seven Samurai',
       'Metropolis', 'Jaws', 'Up', 'Shazam!', 'The Dark Knight',
       'The Treasure of the Sierra Madre', 'Blade Runner 2049',
       'The 39 Steps', 'Captain America: Civil War', 'The Jungle Book',
       'Harry Potter and the Deathly Hallows: Part 2', 'Skyfall',
       'Lawrence of Arabia', 'Mission: Impossible Rogue Nation',
       'Apocalypse Now', 'The Hurt Locker', 'The LEGO Movie', 'Star Trek',
       'Moana', 'Avengers: Infinity War', 'Ant-Man and The Wasp',
       'Star Wars', 'Is

In [17]:
df.describe()

Unnamed: 0         year  critic_score  people_score  total_reviews
count  1610.000000  1610.000000   1610.000000   1609.000000    1610.000000
mean    804.500000  1991.745963     92.693789     83.405221     143.652174
std     464.911282    28.054120     11.621759     11.263792     118.137144
min       0.000000  1919.000000      2.000000     10.000000      39.000000
25%     402.250000  1969.000000     92.000000     80.000000      56.000000
50%     804.500000  2005.000000     96.000000     87.000000      90.000000
75%    1206.750000  2014.000000     98.000000     91.000000     205.750000
max    1609.000000  2020.000000    100.000000     98.000000     561.000000

In [18]:
df['type'].unique()

array(['Action & Adventure', 'Animation', 'Art House & International',
       'Classics', 'Comedy', 'Documentary', 'Drama', 'Horror',
       'Kids & Family', 'Musical & Performing Arts', 'Mystery & Suspense',
       'Romance', 'Science Fiction & Fantasy', 'Special Interest',
       'Sports & Fitness', 'Television', 'Western'], dtype=object)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                1610 non-null   int64  
 1   title                     1610 non-null   object 
 2   year                      1610 non-null   int64  
 3   synopsis                  1602 non-null   object 
 4   critic_score              1610 non-null   int64  
 5   people_score              1609 non-null   float64
 6   consensus                 1593 non-null   object 
 7   total_reviews             1610 non-null   int64  
 8   total_ratings             1610 non-null   object 
 9   type                      1610 non-null   object 
 10  rating                    1139 non-null   object 
 11  genre                     1603 non-null   object 
 12  original_language         1570 non-null   object 
 13  director                  1609 non-null   object 
 14  producer

In [20]:
df.shape


(1610, 26)

In [21]:
df[df["type"]=="Animation"].head()

Unnamed: 0                              title  year  \
100         100                        Toy Story 4  2019   
101         101  Spider-Man: Into the Spider-Verse  2018   
102         102                         Inside Out  2015   
103         103                               Coco  2017   
104         104    Snow White and the Seven Dwarfs  1937   

                                              synopsis  critic_score  \
100  Woody, Buzz Lightyear and the rest of the gang...            97   
101  Bitten by a radioactive spider in the subway, ...            97   
102  Riley (Kaitlyn Dias) is a happy, hockey-loving...            98   
103  Despite his family's generations-old ban on mu...            97   
104  The Grimm fairy tale gets a Technicolor treatm...            98   

     people_score                                          consensus  \
100          94.0  Heartwarming, funny, and beautifully animated,...   
101          93.0  Spider-Man: Into the Spider-Verse matches bold...   
102          89.0  Inventive, gorgeously animated, and powerfully...   
103          94.0  Coco's rich visual pleasures are matched by a ...   
104          78.0  With its involving story and characters, vibra...   

     total_reviews     total_ratings       type  \
100            450  50,000+ Verified  Animation   
101            387           10,000+  Animation   
102            375          100,000+  Animation   
103            347           25,000+  Animation   
104             52          250,000+  Animation   

                                                rating  \
100                                                  G   
101  PG (Mild Language|Frenetic Action Violence|The...   
102            PG (Some Action|Mild Thematic Elements)   
103                             PG (Thematic Elements)   
104                                                  G   

                                                 genre original_language  \
100  comedy, fantasy, animation, kids and family, a...           English   
101  action, adventure, fantasy, comedy, kids and f...           English   
102        kids and family, comedy, fantasy, animation           English   
103  comedy, music, animation, kids and family, adv...           English   
104                kids and family, animation, fantasy           English   

                                          director  \
100                                    Josh Cooley   
101  Bob Persichetti, Peter Ramsey, Rodney Rothman   
102                                    Pete Docter   
103                                    Lee Unkrich   
104                                     David Hand   

                                              producer  \
100           Mark Nielsen, Jonas Rivera, Galyn Susman   
101  Avi Arad, Amy Pascal, Phil Lord, Christopher M...   
102                                       Jonas Rivera   
103                                  Darla K. Anderson   
104                                        Walt Disney   

                                                writer  \
100                    Andrew Stanton, Stephany Folsom   
101                          Phil Lord, Rodney Rothman   
102              Pete Docter, Meg LeFauve, Josh Cooley   
103                     Adrian Molina, Matthew Aldrich   
104  Ted Sears, Richard Creedon, Otto Englander, Di...   

    release_date_(theaters) release_date_(streaming) box_office_(gross_usa)  \
100       Jun 21, 2019 wide              Oct 1, 2019                $434.0M   
101       Dec 14, 2018 wide              Mar 7, 2019                $190.2M   
102       Jun 19, 2015 wide              Nov 3, 2015                  $2.0M   
103       Nov 22, 2017 wide             Feb 13, 2018                $210.5M   
104                     NaN              Sep 1, 2016                    NaN   

    runtime                                      production_co  \
100  1h 40m                            Pixar Animation Studios   
101  1h 57m  Lord Miller, Sony Pict

In [22]:
df['genre'].value_counts()

documentary                                 227
drama                                       126
comedy                                       54
horror                                       48
comedy, drama                                44
                                           ... 
gay and lesbian, drama, history, romance      1
kids and family, comedy, other                1
kids and family, action, adventure            1
western, adventure                            1
adventure, fantasy, kids and family           1
Name: genre, Length: 266, dtype: int64

In [23]:
df['genre']=df['genre'].fillna("Missing").map(lambda x:x.split(',')[0])

In [24]:
df

Unnamed: 0                              title  year  \
0              0                      Black Panther  2018   
1              1                  Avengers: Endgame  2019   
2              2     Mission: Impossible -- Fallout  2018   
3              3                 Mad Max: Fury Road  2015   
4              4  Spider-Man: Into the Spider-Verse  2018   
...          ...                                ...   ...   
1605        1605                             Priest  2011   
1606        1606                     September Dawn  2006   
1607        1607                   American Outlaws  2001   
1608        1608                          Jonah Hex  2010   
1609        1609                      Texas Rangers  2001   

                                               synopsis  critic_score  \
0     After the death of his father, T'Challa return...            96   
1     Adrift in space with no food or water, Tony St...            94   
2     Ethan Hunt and the IMF team join forces with C...            97   
3     Years after the collapse of civilization, the ...            97   
4     Bitten by a radioactive spider in the subway, ...            97   
...                                                 ...           ...   
1605  In a society ravaged by centuries of war betwe...            15   
1606  In 1857 Capt. Alexander Fancher leads a wagon ...            16   
1607  After the Civil War ends, Confederate soldiers...            14   
1608  Having cheated death, gunslinger and bounty hu...            12   
1609  Texas, 1875. In a land without justice, where ...             2   

      people_score                                          consensus  \
0             79.0  Black Panther elevates superhero cinema to thr...   
1             90.0  Exciting, entertaining, and emotionally impact...   
2             88.0  Fast, sleek, and fun, Mission: Impossible - Fa...   
3             86.0  With exhilarating action and a surprising amou...   
4             93.0  Spider-Man: Into the Spider-Verse matches bold...   
...            ...                                                ...   
1605          46.0  Sleek and stylish, but those qualities are was...   
1606          49.0  With its jarring editing, dull love story, and...   
1607          68.0  With corny dialogue, revisionist history, anac...   
1608          20.0  Josh Brolin gives it his best shot, but he can...   
1609          29.0  As far as westerns go, Texas Rangers is strict...   

      total_reviews total_ratings                type  \
0               519       50,000+  Action & Adventure   
1               538       50,000+  Action & Adventure   
2               433       10,000+  Action & Adventure   
3               427      100,000+  Action & Adventure   
4               387       10,000+  Action & Adventure   
...             ...           ...                 ...   
1605            101       50,000+             Western   
1606             55        5,000+             Western   
1607            103       25,000+             Western   
1608            152      100,000+             Western   
1609             51        5,000+             Western   

                                                 rating                 genre  \
0     PG-13 (Sequences of Action Violence|A Brief Ru...             adventure   
1     PG-13 (Sequences of Sci-Fi Violence|Action|Som...                sci fi   
2     PG-13 (Intense Sequences of Action|Brief Stron...                action   
3     R (Intense Sequences of Violence|Disturbing Im...             adventure   
4     PG (Mild Language|Frenetic Action Violence|The...                action   
...                                                 ...                   ...   
1605  PG-13 (Disturbing Images|Brief Strong Language...                horror   
1606                                       R (Violence)                 drama   
1607                           PG-13 (Western Violence)               western   
1608  PG-13 (Intense Seq

In [25]:
movie_user_likes = "Black Panther"
def get_index_from_title(title):
    return df[df.title == title].values[0]
movie_index = get_index_from_title(movie_user_likes)

In [26]:
df.columns

Index(['Unnamed: 0', 'title', 'year', 'synopsis', 'critic_score',
       'people_score', 'consensus', 'total_reviews', 'total_ratings', 'type',
       'rating', 'genre', 'original_language', 'director', 'producer',
       'writer', 'release_date_(theaters)', 'release_date_(streaming)',
       'box_office_(gross_usa)', 'runtime', 'production_co', 'sound_mix',
       'aspect_ratio', 'view_the_collection', 'crew', 'link'],
      dtype='object')

In [27]:
features=['type','rating','genre']

for feature in features:
    df[feature] = df[feature].fillna('')

In [28]:
def combined_features(row):
    return str(row['rating'])+" "+str(row['type'])+" "+row['genre']
df["combined_features"] = df.apply(combined_features, axis =1)

In [29]:
df["combined_features"]

0       PG-13 (Sequences of Action Violence|A Brief Ru...
1       PG-13 (Sequences of Sci-Fi Violence|Action|Som...
2       PG-13 (Intense Sequences of Action|Brief Stron...
3       R (Intense Sequences of Violence|Disturbing Im...
4       PG (Mild Language|Frenetic Action Violence|The...
                              ...                        
1605    PG-13 (Disturbing Images|Brief Strong Language...
1606                           R (Violence) Western drama
1607             PG-13 (Western Violence) Western western
1608    PG-13 (Intense Sequences of Action|Disturbing ...
1609             PG-13 (Western Violence) Western western
Name: combined_features, Length: 1610, dtype: object

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 3 0]
 [1 0 0 ... 0 1 0]
 [1 0 0 ... 0 3 0]]


In [31]:

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(count_matrix)


In [32]:
movie_user_likes = "Inside Out"
def get_index_from_title(title):
    return df[df.title == title].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

In [33]:
movie_index

102

In [34]:
similar_movies = list(enumerate(cosine_sim[movie_index]))


In [35]:
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)


In [36]:
sorted_similar_movies

[(102, 0.9999999999999999),
 (803, 0.8981462390204985),
 (112, 0.8944271909999159),
 (107, 0.8581163303210333),
 (105, 0.7999999999999999),
 (183, 0.7999999999999999),
 (833, 0.7999999999999999),
 (197, 0.762770071396474),
 (415, 0.762770071396474),
 (16, 0.7606388292556648),
 (114, 0.7378647873726218),
 (131, 0.7378647873726218),
 (139, 0.7378647873726218),
 (171, 0.7378647873726218),
 (1459, 0.7378647873726218),
 (807, 0.7348469228349533),
 (862, 0.7302967433402215),
 (125, 0.7171371656006361),
 (898, 0.7115124735378854),
 (184, 0.7071067811865475),
 (875, 0.7071067811865475),
 (159, 0.7016464154456235),
 (802, 0.7016464154456235),
 (186, 0.7),
 (413, 0.7),
 (786, 0.7),
 (817, 0.6761234037828132),
 (831, 0.6761234037828132),
 (839, 0.6761234037828132),
 (841, 0.6761234037828132),
 (870, 0.6761234037828132),
 (858, 0.670820393249937),
 (195, 0.6708203932499369),
 (167, 0.6674238124719147),
 (191, 0.6674238124719147),
 (852, 0.6674238124719147),
 (1458, 0.6674238124719147),
 (855, 0.65

In [39]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
i=0
movie_names=[]
for movie in sorted_similar_movies:
    movie_names.append(get_title_from_index(movie[0]))
    i=i+1
    if i>15:
        break

In [41]:
set(movie_names)

{'Arthur Christmas',
 'Finding Dory',
 'Frankenweenie',
 'Inside Out',
 'Onward',
 'Paddington 2',
 'The Iron Giant',
 'The LEGO Movie',
 'The Perfect Game',
 'Wreck-It Ralph',
 'Zootopia'}

In [38]:
df[df["title"]=="Star Trek"]

Unnamed: 0      title  year  \
38            38  Star Trek  2009   
1235        1235  Star Trek  2009   

                                               synopsis  critic_score  \
38    Aboard the USS Enterprise, the most-sophistica...            94   
1235  Aboard the USS Enterprise, the most-sophistica...            94   

      people_score                                          consensus  \
38            91.0  Star Trek reignites a classic franchise with a...   
1235          91.0  Star Trek reignites a classic franchise with a...   

      total_reviews total_ratings                       type  \
38              354      250,000+         Action & Adventure   
1235            354      250,000+  Science Fiction & Fantasy   

                                                 rating      genre  \
38    PG-13 (Sci-Fi Action|Brief Sexual Content|Viol...  adventure   
1235  PG-13 (Sci-Fi Action|Brief Sexual Content|Viol...  adventure   

     original_language     director                     producer  \
38             English  J.J. Abrams  J.J. Abrams, Damon Lindelof   
1235           English  J.J. Abrams  J.J. Abrams, Damon Lindelof   

                           writer release_date_(theaters)  \
38    Roberto Orci, Alex Kurtzman        May 7, 2009 wide   
1235  Roberto Orci, Alex Kurtzman        May 7, 2009 wide   

     release_date_(streaming) box_office_(gross_usa) runtime production_co  \
38                Aug 1, 2013                $257.7M   2h 6m     Bad Robot   
1235              Aug 1, 2013                $257.7M   2h 6m     Bad Robot   

     sound_mix aspect_ratio view_the_collection  \
38         NaN          NaN           Star Trek   
1235       NaN          NaN           Star Trek   

                                                   crew  \
38    Chris Pine, Zachary Quinto, Leonard Nimoy, Eri...   
1235  Chris Pine, Zachary Quinto, Leonard Nimoy, Eri...   

                                              link  \
38    http://www.rottentomatoes.com/m/star_trek_11   
1235  http://www.rottentomatoes.com/m/star_trek_11   

                                      combined_features  
38    PG-13 (Sci-Fi Action|Brief Sexual Content|Viol...  
1235  PG-13 (Sci-Fi Action|Brief Sexual Content|Viol...